### PR TITLE
Allow download from all domains

### PR DESCRIPTION
**Pull request by sdimodica**

### CODE REVIEW

**Comment by sdimodica** [comment]
How to set ${NPM_TOKEN} in order to let Travis build correctly?

**Comment by lemoustachiste** [comment]
Thanks for your contribution. 
For more context around the Travis build, here is the documentation from Travis: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions.
At this moment I don't have a proposition. We could indeed turn off checks, but that does not seem ideal, or we could always take on the work and put it on a local branch ourselves, but that also seems like more work. I think we need to research how others are doing it.

In this case we will need to retake your commits and follow the https://gist.github.com/stephenparish/9941e89d80e2bc58a153 for semantic-release to work, so probably better to do it like that.

Lastly, could you explicit why you are doing this? https://github.com/blockchain-certificates/blockcerts-verifier/pull/39/commits/451e1028f1262bad68e5be347812321bfd4aacec

Thanks

**Comment by sdimodica** [comment]
Hi @lemoustachiste,
in https://github.com/blockchain-certificates/blockcerts-verifier/commit/451e1028f1262bad68e5be347812321bfd4aacec I'm setting _locale: auto_ because the _cert-verifier-js_ dependency has a default en language and if it is used in another module you cannot change the language itself.
With this commit this will be detected automatically from the browser.

I hope I explained myself...:)

For the Travis security restrictions, I wait for your news.

Thank you,
Salvatore

**Comment by raiseandfall** [comment]
Hi @sdimodica, first of all thanks for contributing to the project!
One quick note about `cert-verifier-js` locale: it only accepts certain values from the following file:
https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/data/i18n.json

At the time of writing, we support `en-US, es-ES, mt, it-IT`. Using `auto` will make the localization fail.

You can retrieve the list of available locales by using `getSupportedLanguages()`: 
https://github.com/blockchain-certificates/cert-verifier-js#i18n

**Comment by sdimodica** [comment]
> 
> 
> Hi @sdimodica, first of all thanks for contributing to the project!
> One quick note about `cert-verifier-js` locale: it only accepts certain values from the following file:
> https://github.com/blockchain-certificates/cert-verifier-js/blob/master/src/data/i18n.json
> 
> At the time of writing, we support `en-US, es-ES, mt, it-IT`. Using `auto` will make the localization fail.
> 
> You can retrieve the list of available locales by using `getSupportedLanguages()`:
> https://github.com/blockchain-certificates/cert-verifier-js#i18n

Hi @raiseandfall,
if the locale is not supported, then the default is en, so localization doesn't fail.

What am I doing wrong?

Thank you,
Salvatore

**Comment by raiseandfall** [comment]
Hi @sdimodica 
Actually I was mistaken first. I understand. 
Your change would make the blockcerts verifier automatically detect the locale from the browser. @lemoustachiste What's your input on this? Does it sound good to you?
Thanks

**Comment by lemoustachiste** [comment]
sounds good.  I'll see if I have time to take the PR today

**Comment by lemoustachiste** [comment]
handled by https://github.com/blockchain-certificates/blockcerts-verifier/pull/41

**Pull request closed without merging**
