### PR TITLE
feat(i18n): add japanese translations

### PR DESCRIPTION
**Pull request by amazanzan**

### CODE REVIEW

**Comment by lemoustachiste** [comment]
Hey, 

thanks for this. I don't speak japanese so I need to get this reviewed before I can merge it.

However this week with Thanksgiving being there it might prove difficult and we might have to wait until next week. Sorry about that.

**Comment by amazanzan** [comment]
@lemoustachiste thanks for the swift reply. If you'd like me to find someone to review the translations just let me know.

**Comment by lemoustachiste** [comment]
Hey, could you rewrite the commit to follow the angular convention so it can trigger a new release?

Something like `feat(i18n): add japanese support`?

Thanks

**Comment by amazanzan** [comment]
@lemoustachiste done!

**Comment by amazanzan** [comment]
Closing due to resubmission as requested in new PR #1524

**Pull request closed without merging**
