### PR TITLE
feat(NewComponent): add blockcerts-certificate component

### PR DESCRIPTION
**Pull request by raulgomezc**
Hey, 

I needed to use the library but I didn't want to use the whole verifying component wrapper, so I exposed a plain certificate that takes in the data directly.

I've never used polymer nor LitElement so if any changes need to be made please lemme know.

BTW, tests are crashing on master as far as I know so, that's why I didn't fix them. Not sure if it's maybe my node version, but I'm using the one on the `.nvmrc`.

### CODE REVIEW

**Comment by lemoustachiste** [comment]
Hi @raulgomezc, thanks for the contribution. 

So what you are essentially trying to do is render a certificate that would be passed as a string (not from a file nor a URL?), and have it rendered? 

I think this is could be done in a simpler way than duplicating code and behaviors, of which I am not necessarily in favor.

Disabling the verification can be done with the flag: `disable-verify` passed to the component so I would say let's reuse that, and let's avoid having a whole new component exposed in the final output, otherwise we are opening the door to a confusing world. This Verifier should capable of accommodating as many use cases as possible without having the need for a new component for each one of them.

I like the idea of being able to specify the certificate as a string directly and reduce initial load time, so I'm ok with the new API option (provided you also update the Readme and add a Demo - try and add a component test too). The idea would be to set it in the state directly which shouldn't be complicated in the current state of things (you are basically already doing it).

Tests work but are unreliable :(. They may or may not fail, not because of the code but because of latency, which then makes it confusing to figure out what actually happened. One solution is to use contract testing/mock server to simulate whatever cert-verifier-js does, but I am not sure we can do that in the Polymer test suite, and don't have time to dedicate to this at this moment. 

Do the proposed changes sound acceptable to you?

Thanks again

**Comment by raulgomezc** [comment]
Basically yes, that's what I'm trying to do.

Won't the `disable-verify` disable the verification modal as well? I just don't want the wrapper to appear, input, drag'n drop, and so on, but I get the idea of not duplicating code, I could try and work around the wrapper tho.

Sure, the changes seem reasonable. Will close this PR and put the changes in another one.

Thanks!

**Comment by lemoustachiste** [comment]
I think as long as the certificate is initially loaded, you shouldn't see
any of the input, just the rendered certificate.
We need to also add a way to prevent verification of other certificates,
unless you are fine with the link being there. This could be a second PR
though.

**Comment by raulgomezc** [comment]
I'll just put in a flag for the footer as well

**Pull request closed without merging**
